import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Sidebar from "./Interfaces/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const links = [
    { href: "/homepage", label: "Homepage" },
    { href: "/taskboard", label: "Task Board" },
    { href: "/userprofile", label: "User Profile" },
  ];
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <nav className="bg-slate-900 p-4 hidden lg:flex justify-center">
          {links.map((link) => (
            <Link key={link.href} href={link.href} className="text-white mr-4">
              {link.label}
            </Link>
          ))}
        </nav> */}
        <Sidebar links={links} />
        <div className="p-6">
          {children}
        </div>
      </body>
    </html>
  );
}
