"use client";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Sidebar from "./Interfaces/sidebar";
import { TasksProvider } from "./Interfaces/taskContext";
import { useRouter } from "next/navigation";
import { usePathname } from "next/navigation"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname()
  const links = [
    { href: "/homepage", label: "Homepage" },
    { href: "/taskboard", label: "Task Board" },
    { href: "/userprofile", label: "User Profile" },
  ];

  const isHomepage = pathname === "/homepage";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TasksProvider>
          <Sidebar links={links} />
          <div>
            {children}
          </div>
        </TasksProvider>
      </body>
    </html>
  );
}
